// Copyright (c) 2017 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
:projectid: rest-hateoas
:page-layout: guide
:page-duration: 30 minutes
:page-description: Learn how to build a hypermedia-driven RESTful web service
:page-tags: ['REST', 'HATEOAS']
:page-permalink: /guides/{projectid}
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
= Creating a Hypermedia-driven RESTful web service

Explore how to use Hypermedia As The Engine Of Application State (HATEOAS) to drive your
RESTful web service on top of Open Liberty.


// =================================================================================================
// Introduction
// =================================================================================================

== What you'll learn

You will learn how to use hypermedia to create a specific style of a response JSON, the contents
of which are used to navigate your REST service. You'll be building on top of a simple inventory
REST service developed with MicroProfile technologies, providing a service at the following URL:

```
http://localhost:9080/inventory/hosts
```

The service responds with a JSON containing an array of registered hosts, each with a collection
of HATEOAS links:

[source, json, role="no_copy"]
----
[
  {
    "hostname": "foo",
    "_links": [
      {
        "href": "http://localhost:9080/inventory/hosts/foo",
        "rel": "self"
      }
    ]
  },
  {
    "hostname": "bar",
    "_links": [
      {
        "href": "http://localhost:9080/inventory/hosts/bar",
        "rel": "self"
      }
    ]
  },
  {
  "hostname": "*",
  "_links": [
    {
      "href": "http://localhost:9080/inventory/hosts/*",
      "rel": "self"
    }
  ]
  }
]
----

=== What is HATEOAS?

Hypermedia As The Engine Of Application State (HATEOAS) is a constrained form of REST application architecture.
With HATEOAS, the client receives information about the available resources from the REST application.
This means the client does not need to be hard-coded to a fixed set of resources and the application
and client can evolve independently. In other words, the application tells the client where it can go
and what it can access by providing it with a simple collection of links to other available resources.

=== Response JSON

When you build a RESTful web service, it is important to consider the style of your response files.
Whether they are JSON files, XML files, or in some other format, a good practice is to always have them in
a clean and organized form. In the context of HATEOAS, each resource must contain a link reference to
itself, commonly referred to as `self`. Each link must also have a relationship associated with it,
although no strict rules exist as to how this relationship must be formatted. The collection
of such links must be contained with a `_links` array, which itself must be a direct property of the
resource object. The underscore is used so that the `_links` property does not collide with any
existing fields named `links`. The structure of HATEOAS links that you will be using in this
guide is the following one:

[source, json, role="no_copy"]
----
  "_links": [
    {
      "href": ,
      "rel":
    }
  ]
----

==== Link types

In the following example there are two different links. The first has a `self` relationship with the
resource object and is generated whenever a host has been registered. The link points to that host
entry in the inventory:

[source, json, role="no_copy"]
----
  {
    "href": "http://localhost:9080/inventory/hosts/<hostname>",
    "rel": "self"
  }
----

The second link has a `properties` relationship with the resource object and is generated
if the host `system` service is running. The link points to the properties resource on the host:

[source, json, role="no_copy"]
----
  {
    "href": "http://<hostname>:9080/system/properties",
    "rel": "properties"
  }
----

==== Other formats

Although you should stick to the previous format for the purpose of this guide, another common
convention has the link as the value of the relationship:

[source, json, role="no_copy"]
----
  "_links": {
      "self": "http://localhost:9080/inventory/hosts/<hostname>",
      "properties": "http://<hostname>:9080/system/properties"
  }
----


include::{common-includes}/gitclone.adoc[]


// =================================================================================================
// Guide
// =================================================================================================

== Creating the response JSON

Begin by building your response JSON, which is composed of the `_links` array, as well as the name of
the host machine.

=== Linking to inventory contents

As mentioned before, your starting point is an existing simple inventory REST service. You can learn
more about this service and how to build it by visiting https://openliberty.io/guides/microprofile-intro.html[Creating a MicroProfile application].

First, you must tweak the request handlers in the `InventoryResource` class. Since the `.../inventory/hosts/`
URL will no longer respond with a JSON representation of the contents of your inventory, the `listContents`
method can be discarded and instead be integrated into the `getPropertiesForHost` method:

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/microprofile/InventoryResource.java[tags=getPropertiesForHost]
----

The contents of your inventory are now under the `*` wildcard and reside at the following URL:

[source, role="no_copy"]
----
http://localhost:9080/inventory/hosts/*
----

Next, add a simple `GET` request handler that is responsible for handling all `GET` requests that are
made to our target URL. This method responds with a JSON containing HATEOAS links:

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/microprofile/InventoryResource.java[tags=handler]
----

You also need a `UriInfo` object, which you use to build your HATEOAS links:

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/microprofile/InventoryResource.java[tags=uriinfo]
----

The `@Context` annotation is a part of CDI and indicates that the UriInfo will be injected when the
resource is instantiated.

Your new `InventoryResource` class is now finished. Next, let's implement the `getSystems` method and build
the response JSON object.

=== Linking to each available resource

Let's implement the `getSystems` method in your `InventoryManager` class. This method accepts a
target URL as an argument and returns a JSON object that contains HATEOAS links.

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/microprofile/InventoryManager.java[tags=getSystems]
----

The `buildHostJson` helper method builds the actual JSON object. Use this method, together with a
simple map function, to create an array of the JSON objects for each system.

Let's implement the `buildHostJson` helper in the `InventoryUtil` class:

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/microprofile/util/InventoryUtil.java[tags=buildHostJson]
----

You're creating a JSON object that contains the name of your host system and the `_links` array, which
is generated separately in another helper:

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/microprofile/util/InventoryUtil.java[tags=buildLinksForHost]
----

This helper accepts a host name and a target URL as arguments and builds a link that points to the
inventory entry with a `self` relationship, as well as a link that points to the `system` service with
a `properties` relationship:

* `http://localhost:9080/inventory/hosts/<hostname>`
* `http://<hostname>:9080/system/properties`

=== Linking to inactive services or unavailable resources

Consider what happens when one of the return links does not work or when a link should be available
for one object but not for another. In other words, it is important that a resource or service is
available and running before it is linked in the `_links` array.

Although this guide does not cover this case, you should nevertheless always make sure that you receive
a good response code from a service before linking that service. Similarly, it is also important that
it makes sense for a particular object to access a resource it is linked to. For instance, it wouldn't
make sense for an account holder to be able to withdraw money from their account when their balance is 0.
Hence, they should not be linked to a resource which provides money withdrawal.


include::{common-includes}/mvnbuild.adoc[]


// =================================================================================================
// Starting the application
// =================================================================================================

== Starting the application

To see the new application in action, run the Maven `liberty:start-server` command from the `start` directory:

[source, role="no_copy"]
----
cd start
mvn liberty:start-server
----

After the server is running, you can find your new Hypermedia-driven `inventory` service at the following URL:

* `http://localhost:9080/inventory/hosts`


// =================================================================================================
// Testing
// =================================================================================================

== Testing the hypermedia-driven RESTful web service

The `inventory` service that is now hypermedia-driven can be accessed at the following URLs:

* `http://localhost:9080/inventory/hosts`
* `http://localhost:9080/inventory/hosts/{hostname}`

The first URL returns the current contents of the inventory and the second the system properties for
the given host name. If the inventory does not contain an entry for the host name specified in the URL,
then the `system` service that is running on the requested host name is called instead. The system
properties are retrieved from that `system` service and then stored in the inventory and returned.

If you have the servers running, you can point your browser to each of the previous URLs to test the
application manually. Nevertheless, you should always rely on automated tests since they are more reliable
and will always trigger a failure in the event a change introduces a defect.

=== Setting up your tests

Create a test class `src/test/java/it/io/openliberty/guides/hateoas/EndpointTest.java`

You can use the `@Before` and `@After` annotations to perform any setup and teardown tasks for each
of your individual tests.

[source, java]
----
include::finish/src/test/java/it/io/openliberty/guides/hateoas/EndpointTest.java[tags=**;!comment;!class-contents;setup]
----

=== Writing the tests

Each test method must be marked with the `@Test` annotation. Typically, the execution order of test
methods is not controlled, but if control is required, methods can be placed in a single container test
method. This container method is then the only one marked with the `@Test` annotation. The following
test suite contains two test methods, which are run in the order they appear:

[source, java, indent=0]
----
include::finish/src/test/java/it/io/openliberty/guides/hateoas/EndpointTest.java[tags=testSuite]
----

Create a test called `testLinkForInventoryContents`. This test is responsible for asserting that
the correct HATEOAS link is created for the inventory contents.

[source, java, indent=0]
----
include::finish/src/test/java/it/io/openliberty/guides/hateoas/EndpointTest.java[tags=testLinkForInventoryContents]
----

Write a `getResponse` helper method to reuse the same line of code for retrieving a response from a
given URL. This technique helps keep your code neat and organized:

[source, java, indent=0]
----
include::finish/src/test/java/it/io/openliberty/guides/hateoas/EndpointTest.java[tags=getResponse]
----

Write another helper method called `assertResponse`. This method ensures that the response code that you receive is
valid (200):

[source, java, indent=0]
----
include::finish/src/test/java/it/io/openliberty/guides/hateoas/EndpointTest.java[tags=assertResponse]
----

Create a test called `testLinksForSystem`. This test is responsible for asserting that the correct
HATEOAS links are created for the `localhost` system. This method checks for both the `self` link, pointing
to the `inventory` service, and the `properties` link, pointing to the `system` service running on the
`localhost`.

[source, java, indent=0]
----
include::finish/src/test/java/it/io/openliberty/guides/hateoas/EndpointTest.java[tags=testLinksForSystem]
----

Write a helper method called `visitLocalhost`. This method creates a `GET` request to the
`system` service, registering localhost:

[source, java, indent=0]
----
include::finish/src/test/java/it/io/openliberty/guides/hateoas/EndpointTest.java[tags=visitLocalhost]
----

=== Running the tests

To rebuild and run the tests, navigate to the `start` directory and run the `mvn clean install` command
from the command line.

[source, role="no_copy"]
----
# If the server is still running from previous steps, stop it first:
mvn liberty:stop-server

# Then run the following command:
mvn clean install
----

Some time might elapse before the tests finish running. If the tests pass, you will see the following
output:

[source, role="no_copy"]
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.hateoas.EndpointTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.086 sec - in it.io.openliberty.guides.hateoas.EndpointTest

Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
----


== Great work! You're done!

You've just built and tested a hypermedia-driven RESTful web service on top of Open Liberty.


include::{common-includes}/finish.adoc[]
