// Copyright (c) 2017 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
:projectid: rest-hateoas
:page-layout: guide
:page-duration: 30 minutes
:page-releasedate: 2017-09-19
:page-description: Learn how to build a hypermedia-driven RESTful web service
:page-tags: ['REST', 'HATEOAS']
:page-related-guides: ['rest-intro', 'microprofile-intro']
:page-permalink: /guides/{projectid}
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
= Creating a hypermedia-driven RESTful web service

// =================================================================================================
// Introduction
// =================================================================================================

Explore how to use hypermedia as the engine of application state (HATEOAS) to drive your RESTful web
services in Open Liberty

== What you'll learn

You will learn how to utilize HATEOAS to create a specific style of response JSON, whose contents
can be used to navigate your REST service without the need of any external documentation or knowledge
about how the service is structured. You will build on top of a simple inventory service and extend
it to use hypermedia. To learn more about this service as well as how you can build it yourself,
read https://openliberty.io/guides/microprofile-intro.html[Creating a MicroProfile application].

Your inventory service will be located at the following URL:

```
http://localhost:9080/inventory/hosts
```

Which will respond with a JSON containing a list of hosts currently stored in the inventory, each
with a collection of hypermedia links:

[source, JSON, role="no_copy"]
----
[
  {
    "hostname": "foo",
    "_links": {
      "self": "http://localhost:9080/inventory/hosts/localhost",
      "properties": "http://foo:9080/system/properties"
    }
  },
  {
    "hostname": "bar",
    "_links": {
      "self": "http://localhost:9080/inventory/hosts/localhost",
      "properties": "http://bar:9080/system/properties"
    }
  },
  {
    "hostname": "*",
    "_links": {
      "self": "http://localhost:9080/inventory/hosts/*"
    }
  }
]
----

=== What is HATEOAS?

HATEOAS is a constrained form of REST application architecture. With HATEOAS, a client receives
a list of all resources it can access from the REST application. It can then use this list to
navigate the application's resources without needing to know where these resources are actually located.
In other words, a client doesn't need to know beforehand at what endpoints various resources
are served. Instead, its given a list of URLs which it can access from the current endpoint.

=== Response JSON

With HATEOAS, you are going to tweak the existing response JSON at the `/hosts` endpoint to include
hypermedia links. Each such link will be in form `<rel>:<href>` where `rel` is the relationship
between the link and the resource its attached to, and `href` is the link to the resource itself.
As a general convention,
every resource must contain a link reference to itself defined by the relationship `self`. As another
convention, all hypermedia links are stored inside a `_links` array.

Note, you may find that there are a variety of ways of styling the `_links` array. Any format is
acceptable although you should stick to the `<rel>:<href>` format for this guide. This format also
makes it much easier to access the links using the relationships as keys.

// =================================================================================================
// Getting started
// =================================================================================================

include::{common-includes}/gitclone.adoc[]


// =================================================================================================
// Try it first
// =================================================================================================

== Try it first

Feel free to try the finished version of what you will be building to get a feel of how everything
will work. To do this, navigate backwards to the `finish` directory and execute the following:

```
mvn clean install liberty:start-server
```

Your hypermedia-driven inventory service will be available at http://localhost:9080/inventory/hosts.
Visiting this URL will return the following JSON:

[source, JSON, indent=0, role="no_copy"]
----
[
  {
    "hostname": "*",
    "_links": {
      "self": "http://localhost:9080/inventory/hosts/*"
    }
  }
]
----

Clicking on the `self` URL will bring you to the original starting point of the MicroProfile guide,
where you will get a JSON listing the current contents of the inventory.

Visit http://localhost:9080/inventory/hosts/localhost to retrieve the system properties of your own
machine's JVM. Next, go back to http://localhost:9080/inventory/hosts and you will see that `localhost`
has been added to the JSON:

[source, JSON, indent=0, role="no_copy"]
----
[
  {
    "hostname": "localhost",
    "_links": {
      "self": "http://localhost:9080/inventory/hosts/localhost",
      "properties": "http://localhost:9080/system/properties"
    }
  },
  {
    "hostname": "*",
    "_links": {
      "self": "http://localhost:9080/inventory/hosts/*"
    }
  }
]
----

The `self` link for `localhost` is used to link to its JVM's system properties, which are currently
stored in the inventory service. The `properties` link is used to link to the system properties service
running on `localhost`, which exposes its JVM's system properties and is accessed by the inventory
service.

If you are at any time confused about what these linked services do, reference the MicroProfile guide
for more information: https://openliberty.io/guides/microprofile-intro.html[Creating a MicroProfile application].


// =================================================================================================
// Guide
// =================================================================================================

== Adding hypermedia links to the response JSON

Begin by tweaking the existing response JSON to include the `_links` array.

=== Linking to the inventory contents

First, since the `/hosts` endpoint will no longer respond with the contents of the inventory, you can
discard the `listContents` method and instead integrate it into the `getPropertiesForHost` method.

Tweak `src/main/java/io/openliberty/guides/microprofile/InventoryResource.java`:

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/microprofile/InventoryResource.java[tags=getPropertiesForHost]
----

The contents of your inventory are now under the asterisk (\*) wildcard and will be located at
http://localhost:9080/inventory/hosts/*

Next, add a simple GET request handler that will handle all GET requests made to the `/hosts` endpoint.
This method will return your new response JSON containing hypermedia links:

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/microprofile/InventoryResource.java[tags=handler]
----

You will also need a `UriInfo` object, which will be useful when building your hypermedia links. Inject
it right after the `InventoryManager` injection:

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/microprofile/InventoryResource.java[tags=uriinfo]
----

The `@Context` annotation is a part of CDI and indicates that the UriInfo will be injected when the
resource is instantiated.

=== Creating the `_links` array

Next, implement the `getSystems` method in the `InventoryManager` class. This method will accept a
target URL as an argument and will return a JSON object that will be your HATEOAS response JSON.

Create `getSystems()` in `src/main/java/io/openliberty/guides/microprofile/InventoryManager.java`:

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/microprofile/InventoryManager.java[tags=getSystems]
----

Implement the `buildHostJson` helper in the `InventoryUtil` class. This helper will build the
actual JSON objects for each host.

Create `buildHostJson()` in `src/main/java/io/openliberty/guides/microprofile/util/InventoryUtil.java`:

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/microprofile/util/InventoryUtil.java[tags=buildHostJson]
----

Create one more helper method called `buildLinksForHost`. This method will be responsible for building
the `_links` array for each host.

Create `buildLinksForHost()` in `src/main/java/io/openliberty/guides/microprofile/util/InventoryUtil.java`:

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/microprofile/util/InventoryUtil.java[tags=buildLinksForHost]
----

=== Linking to inactive services or unavailable resources

Consider what happens when one of the hypermedia links doesn't work or when a link should be available
for one client but not for another. In other words, it's important that a resource/service is
running and makes sense to be accessed by the client before its added to the `_links` array

Although this guide does not cover this case, always make sure that you receive
a good response code from a service before you link that service. Similarly, make sure that
it makes sense for a particular client to access a resource it is linked to. For instance, it wouldn't
make too much sense for an account holder to be able to withdraw money from their account when their
balance is 0. Hence, that account holder should not be linked to a service that provides money
withdrawal.


include::{common-includes}/mvnbuild.adoc[]


// =================================================================================================
// Starting the application
// =================================================================================================

== Starting the application

Now that your application is built, run it to see it in action! To do this, run the Maven `liberty:start-server`
goal from the `start` directory:

```
mvn liberty:start-server
```

After the server starts, you can find your new hypermedia-driven inventory service at
http://localhost:9080/inventory/hosts


// =================================================================================================
// Testing
// =================================================================================================

== Testing what you built

Your new inventory service has the following endpoints:

* http://localhost:9080/inventory/hosts
* http://localhost:9080/inventory/hosts/{hostname}

The first URL returns hypermedia links that can be used to navigate your application, and the second
URL returns the system properties for the specified hostname.

While you can test your application manually, you should always rely on automated tests to catch any
bugs that might come up after new changes are made to the code.

=== Setting up your tests

Create a `src/test/java/it/io/openliberty/guides/hateoas/EndpointTest.java` test class.

You can use the `@Before` and `@After` annotations to perform any setup and teardown tasks for each
of your individual tests:

[source, java]
----
include::finish/src/test/java/it/io/openliberty/guides/hateoas/EndpointTest.java[tags=**;!comment;!class-contents;setup]
----

=== Writing the tests

Create a single test method called `testSuite` and mark it with the `@Test` annotation. Each of your
test cases will go into this method so that they execute in a specific order.

Create `testSuite()` in `src/test/java/it/io/openliberty/guides/hateoas/EndpointTest.java`:

[source, java, indent=0]
----
include::finish/src/test/java/it/io/openliberty/guides/hateoas/EndpointTest.java[tags=testSuite]
----

Create a test case called `testLinkForInventoryContents`. This test case will be responsible for
asserting that the correct `_links` array was generated for the `*` hostname:

[source, java, indent=0]
----
include::finish/src/test/java/it/io/openliberty/guides/hateoas/EndpointTest.java[tags=testLinkForInventoryContents]
----

Write a `getResponse` helper method to reuse the same line of code for retrieving a response from a
specific URL. This will help you keep your code neat and organized:

[source, java, indent=0]
----
include::finish/src/test/java/it/io/openliberty/guides/hateoas/EndpointTest.java[tags=getResponse]
----

Write another helper method called `assertResponse`. This method ensures that you receive a valid
response code of 200:

[source, java, indent=0]
----
include::finish/src/test/java/it/io/openliberty/guides/hateoas/EndpointTest.java[tags=assertResponse]
----

Create a test case called `testLinksForSystem`. This test will be responsible for asserting that the correct
`_links` array was generated for the `localhost` host:

[source, java, indent=0]
----
include::finish/src/test/java/it/io/openliberty/guides/hateoas/EndpointTest.java[tags=testLinksForSystem]
----

Write a helper method called `visitLocalhost`. This method will make a `GET` request to the `localhost's`
`system` service to store its JVM's system properties in the inventory:

[source, java, indent=0]
----
include::finish/src/test/java/it/io/openliberty/guides/hateoas/EndpointTest.java[tags=visitLocalhost]
----

=== Running the tests

If the server is still running from the previous steps, stop it first using the Maven `liberty:stop-server` goal:

```
mvn liberty:stort-server
```

Then, verify that the tests pass using the `verify` goal:

```
mvn verify
```

It may take some time before build is complete. If the tests pass, you will see a similar output:

[source, role="no_copy"]
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.hateoas.EndpointTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.197 sec - in it.io.openliberty.guides.hateoas.EndpointTest

Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
----


== Great work! You're done!

You've just built and tested a hypermedia-driven RESTful web service on top of Open Liberty.


include::{common-includes}/finish.adoc[]
